Siglo_XXI/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('workstation', views.workstation, name='workstation'),
    path('logout', views.logout),

]

main/models.py
from django.db import models

# Create your models here.

#Inicio Scrit.

class ClienteXxi(models.Model):
    id_cliente = models.BigIntegerField(primary_key=True)
    nombre_cli = models.CharField(max_length=30)
    correo_cli = models.CharField(max_length=30)
    telefono_cli = models.BigIntegerField()
    direccion_cli = models.CharField(max_length=50, blank=True, null=True)
    contrasena_cli = models.CharField(max_length=40)

    
    def __str__(self) :
        return self.nombre_cli



class EmpleadosXxi(models.Model):
    id_empleado = models.BigIntegerField(primary_key=True)
    nombre_emp = models.CharField(max_length=15)
    apellido_pat_emp = models.CharField(max_length=15)
    apellido_mat_emp = models.CharField(max_length=15)
    salario = models.BigIntegerField()
    fecha_nac = models.DateField()
    direccion_emp = models.CharField(max_length=30)
    telefono_emp = models.BigIntegerField()
    correo_emp = models.CharField(max_length=30)
    tipo_emplado_xxi_id_tipo_empleado = models.ForeignKey('TipoEmpladoXxi', models.DO_NOTHING, db_column='tipo_emplado_xxi_id_tipo_empleado')
    contrasena_emp = models.CharField(max_length=12)

    
    def __str__(self) :
        return self.nombre_emp

class FacturaXxi(models.Model):
    id_factura = models.BigIntegerField(primary_key=True)
    fecha = models.DateField()
    total = models.BigIntegerField()
    cliente_xxi_id_cliente = models.ForeignKey(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente')
    tipo_pago_xxi_id_tipo_pago = models.ForeignKey('TipoPagoXxi', models.DO_NOTHING, db_column='tipo_pago_xxi_id_tipo_pago')

    
    def __str__(self) :
        return self.fecha

class IngredientesXxi(models.Model):
    id_ingrediente = models.BigIntegerField(primary_key=True)
    ingrediente = models.CharField(max_length=15)
    marca = models.CharField(max_length=12)
    cantidad = models.BigIntegerField()

   
    def __str__(self) :
        return self.ingrediente

class MesaXxi(models.Model):
    id_mesa = models.BigIntegerField(primary_key=True)
    capacidad = models.BigIntegerField()

    
    def __str__(self) :
        return self.capacidad

class OrdenesXxi(models.Model):
    id_orden = models.BigIntegerField(primary_key=True)
    fecha = models.DateField()
    pagado = models.CharField(max_length=1)
    detalle = models.CharField(max_length=20)
    estado = models.CharField(max_length=12)
    cliente_xxi_id_cliente = models.ForeignKey(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente')
    mesa_xxi_id_mesa = models.ForeignKey(MesaXxi, models.DO_NOTHING, db_column='mesa_xxi_id_mesa')

    
    def __str__(self) :
        return self.estado

class ProductosXxi(models.Model):
    id_producto = models.BigIntegerField(primary_key=True)
    nombre = models.CharField(max_length=15)
    precio = models.BigIntegerField()
    tipo_producto_xxi_id_tipo_producto = models.ForeignKey('TipoProductoXxi', models.DO_NOTHING, db_column='tipo_producto_xxi_id_tipo_producto')

    
    def __str__(self) :
        return self.nombre

class ProveedoresXxi(models.Model):
    id_proveedor = models.BigIntegerField(primary_key=True)
    nombre_proveedor = models.CharField(max_length=15)
    telefono = models.BigIntegerField()
    correo = models.CharField(max_length=30)

    
    def __str__(self) :
        return self.nombre_proveedor

class Relation10(models.Model):
    ordenes_xxi_id_orden = models.OneToOneField(OrdenesXxi, models.DO_NOTHING, db_column='ordenes_xxi_id_orden', primary_key=True)
    factura_xxi_id_factura = models.ForeignKey(FacturaXxi, models.DO_NOTHING, db_column='factura_xxi_id_factura')

    


class Relation12(models.Model):
    mesa_xxi_id_mesa = models.OneToOneField(MesaXxi, models.DO_NOTHING, db_column='mesa_xxi_id_mesa', primary_key=True)
    cliente_xxi_id_cliente = models.ForeignKey(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente')

   


class Relation13(models.Model):
    cliente_xxi_id_cliente = models.OneToOneField(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente', primary_key=True)
    reservas_xxi_id_reserva = models.ForeignKey('ReservasXxi', models.DO_NOTHING, db_column='reservas_xxi_id_reserva')

    

class Relation3(models.Model):
    empleados_xxi_id_empleado = models.OneToOneField(EmpleadosXxi, models.DO_NOTHING, db_column='empleados_xxi_id_empleado', primary_key=True)
    ordenes_xxi_id_orden = models.ForeignKey(OrdenesXxi, models.DO_NOTHING, db_column='ordenes_xxi_id_orden')

    


class Relation31(models.Model):
    productos_xxi_id_producto = models.OneToOneField(ProductosXxi, models.DO_NOTHING, db_column='productos_xxi_id_producto', primary_key=True)
    ingredientes_xxi_id_ingrediente = models.ForeignKey(IngredientesXxi, models.DO_NOTHING, db_column='ingredientes_xxi_id_ingrediente')

  


class Relation32(models.Model):
    productos_xxi_id_producto = models.OneToOneField(ProductosXxi, models.DO_NOTHING, db_column='productos_xxi_id_producto', primary_key=True)
    ordenes_xxi_id_orden = models.ForeignKey(OrdenesXxi, models.DO_NOTHING, db_column='ordenes_xxi_id_orden')

    


class Relation33(models.Model):
    ingredientes_xxi_id_ingrediente = models.OneToOneField(IngredientesXxi, models.DO_NOTHING, db_column='ingredientes_xxi_id_ingrediente', primary_key=True)
    proveedores_xxi_id_proveedor = models.ForeignKey(ProveedoresXxi, models.DO_NOTHING, db_column='proveedores_xxi_id_proveedor')

    

class Relation8(models.Model):
    cliente_xxi_id_cliente = models.OneToOneField(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente', primary_key=True)
    ordenes_xxi_id_orden = models.ForeignKey(OrdenesXxi, models.DO_NOTHING, db_column='ordenes_xxi_id_orden')

    


class ReservasXxi(models.Model):
    id_reserva = models.BigIntegerField(primary_key=True)
    fecha_hora = models.DateField()
    cliente_xxi_id_cliente = models.ForeignKey(ClienteXxi, models.DO_NOTHING, db_column='cliente_xxi_id_cliente')

    
    def __str__(self) :
        return self.fecha_hora

class TipoEmpladoXxi(models.Model):
    id_tipo_empleado = models.BigIntegerField(primary_key=True)
    tipo_empleado = models.CharField(max_length=15)

    
    def __str__(self) :
        return self.tipo_empleado

class TipoPagoXxi(models.Model):
    id_tipo_pago = models.BigIntegerField(primary_key=True)
    tipo_pago = models.CharField(max_length=12)

    
    def __str__(self) :
        return self.tipo_pago

class TipoProductoXxi(models.Model):
    id_tipo_producto = models.BigIntegerField(primary_key=True)
    tipo_producto = models.CharField(max_length=15)

    
    def __str__(self) :
        return self.tipo_producto

#Fin Scrit.

main/forms.py
from django import forms
from main.models import *

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as do_logout
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as do_login
from django.http import HttpResponse
from django.template import loader

# Create your views here.

def index (request):
    template = loader.get_template('main/indexx.html')
    context = {}
    return HttpResponse(template.render(context, request))

def login(request):
    
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                do_login(request, user)
                return redirect('/workstation')

    return render(request, "main/login.html", {'form': form})

def workstation (request):
    template = loader.get_template('main/workstation.html')
    context = {}
    return HttpResponse(template.render(context, request))

def logout(request):
    
    do_logout(request)
    
    return redirect('login')

main/templates/main/login.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--========== BOX ICONS ==========-->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <!--========== CSS ==========-->
        <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">

        <!-- Boostratp 4 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Siglo XXI</title>
    </head>
    <body>

        <!--========== SCROLL TOP ==========-->
        <a href="#" class="scrolltop" id="scroll-top">
            <i class='bx bx-chevron-up scrolltop__icon'></i>
        </a>

        <!--========== HEADER ==========-->
        <header class="l-header" id="header">
            <nav class="nav bd-container">
                <a href="/" class="nav__logo">Siglo XXI</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="/" class="nav__link active-link">Home</a></li>
                        <!--li class="nav__item"><a href="registro.html" class="nav__link">Registrarse</a></li-->
                        <!--li class="nav__item"><a href="login.html" class="nav__link">Ingresar</a></li-->

                        <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

    
        <!-- Formulario -->
        <div class="boxForm">
        <form method="POST" >
            <fieldset>
                <legend class="text-center header">¡Ingresa con tu cuenta XXI!</legend>
            <hr>
            <br>
                <!-- <span class="input-group-addon">@</span> -->
            <div class="form-group">
              <label for="exampleInputEmail1">Ingresa tu Nombre de Usuario</label>
              <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Nombre de Usuario" required>
              
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Ingresa tu contraseña</label>
              <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="contraseña" required>
            </div>
            <small id="emailHelp" class="form-text text-muted">Nunca entregaremos tu información a terceros.</small>
            <!-- <div class="form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Recordarme</label>
            </div> -->
                
            
                
        
            <br>
            <div class="form-group">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            
                 
            </div>
            {% csrf_token %}
            
        </fieldset>
        </form>
        </div>
        
        <!--========== FOOTER ==========-->
        <footer class="footer section bd-container">
            <p class="footer__copy">&#169; 2021 Portafolio Web. Todos los derechos reservados</p>
        </footer>

        <!--========== SCROLL REVEAL ==========-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--========== MAIN JS ==========-->
        <script src="{% static 'main/js/main.js' %}"></script>
    </body>
</html>

main/templates/main/workstation.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--========== BOX ICONS ==========-->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <!--========== CSS ==========-->
        <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">

        <!-- Boostratp 4 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Siglo XXI</title>
    </head>
    <body>

        <!--========== SCROLL TOP ==========-->
        <a href="#" class="scrolltop" id="scroll-top">
            <i class='bx bx-chevron-up scrolltop__icon'></i>
        </a>

        <!--========== HEADER ==========-->
        <header class="l-header" id="header">
            <nav class="nav bd-container">
                <a href="workstation" class="nav__logo">Siglo XXI</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        {% if perms.main.add_ingredientesxxi %}
                        <li class="nav__item"><a href="Bodega" class="nav__link active-link">Bodega</a></li>
                        {% endif %}
                        {% if perms.main.add_facturaxxi %}
                        <li class="nav__item"><a href="Finanzas" class="nav__link active-link">Finanzas</a></li>
                        {% endif %}
                        {% if perms.main.add_mesaxxi %}
                        <li class="nav__item"><a href="Cocina" class="nav__link active-link">Cocina</a></li>
                        {% endif %}
                        

                        

                        
                        <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>
                        <li class="nav__item"><div class="nav__link active-link"> | Usuario: {{request.user.first_name}} {{request.user.last_name}} |</div></li>
                        
                        <li class="nav__item"><a href="/logout" class="nav__link active-link">Cerrar Sesion</a></li>

                        

                        
                        

                    </ul>
                    
                        
                    
                </div>

                        


                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
       
        <div class="boxForm">
            <img src="{% static 'main/img/img_workstation.png' %}" alt="img_workstation">

            <!--div class="cleanslate w24tz-current-time w24tz-large" style="display: inline-block !important; visibility: hidden !important; min-width:300px !important; min-height:145px !important;"><p><a href="//24timezones.com/Santiago--de-Chile/hora" style="text-decoration: none" class="clock24" id="tz24-1632107527-c1232-eyJob3VydHlwZSI6IjI0Iiwic2hvd2RhdGUiOiIxIiwic2hvd3NlY29uZHMiOiIxIiwiY29udGFpbmVyX2lkIjoiY2xvY2tfYmxvY2tfY2I2MTQ3ZmMwNzAxMDQwIiwidHlwZSI6ImRiIiwibGFuZyI6ImVzIn0=" title="husos horarios - Santiago  de Chile" target="_blank" rel="nofollow">Santiago  de Chile</a></p><div id="clock_block_cb6147fc0701040"></div></div>
            <script type="text/javascript" src="//w.24timezones.com/l.js" async></script-->
        </div>
        

        <!--========== FOOTER ==========-->
        <footer class="footer section bd-container">
            <p class="footer__copy">&#169; 2021 Portafolio Web. Todos los derechos reservados</p>
        </footer>

        <!--========== SCROLL REVEAL ==========-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--========== MAIN JS ==========-->
        <script src="{% static 'main/js/main.js' %}"></script>
    </body>

</html>

main/templates/main/workstation_bodega.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!--========== BOX ICONS ==========-->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <!--========== CSS ==========-->
        <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">

        <!-- Boostratp 4 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Siglo XXI</title>
    </head>
    <body>

        <!--========== SCROLL TOP ==========-->
        <a href="#" class="scrolltop" id="scroll-top">
            <i class='bx bx-chevron-up scrolltop__icon'></i>
        </a>

        <!--========== HEADER ==========-->
        <header class="l-header" id="header">
            <nav class="nav bd-container">
                <a href="workstation" class="nav__logo">Siglo XXI</a>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        {% if perms.main.add_ingredientesxxi %}
                        <li class="nav__item"><a href="Bodega" class="nav__link active-link">Bodega</a></li>
                        {% endif %}
                        {% if perms.main.add_facturaxxi %}
                        <li class="nav__item"><a href="Finanzas" class="nav__link active-link">Finanzas</a></li>
                        {% endif %}
                        {% if perms.main.add_mesaxxi %}
                        <li class="nav__item"><a href="Cocina" class="nav__link active-link">Cocina</a></li>
                        {% endif %}
                        

                        

                        
                        <li><i class='bx bx-moon change-theme' id="theme-button"></i></li>
                        <li class="nav__item"><div class="nav__link active-link"> | Usuario: {{request.user.first_name}} {{request.user.last_name}} |</div></li>
                        
                        <li class="nav__item"><a href="/logout" class="nav__link active-link">Cerrar Sesion</a></li>

                        

                        
                        

                    </ul>
                    
                        
                    
                </div>

                        


                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>
       
        
        

        <!--========== FOOTER ==========-->
        <footer class="footer section bd-container">
            <p class="footer__copy">&#169; 2021 Portafolio Web. Todos los derechos reservados</p>
        </footer>

        <!--========== SCROLL REVEAL ==========-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--========== MAIN JS ==========-->
        <script src="{% static 'main/js/main.js' %}"></script>
    </body>

</html>